name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker Image
        env:
          ECR_REGISTRY: 449952321810.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: aws-devops-platform-repo
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./app
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 34.201.210.235
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            aws ecr get-login-password --region us-east-1 | sudo docker login \
              --username AWS \
              --password-stdin 449952321810.dkr.ecr.us-east-1.amazonaws.com
            sudo docker pull 449952321810.dkr.ecr.us-east-1.amazonaws.com/aws-devops-platform-repo:latest
            sudo docker stop aws-devops-app || true
            sudo docker rm aws-devops-app || true
            sudo docker run -d \
              --name aws-devops-app \
              --restart always \
              -p 3000:3000 \
              -e VERSION=${{ github.sha }} \
              449952321810.dkr.ecr.us-east-1.amazonaws.com/aws-devops-platform-repo:latest
